# !! File must end with empty line !!
dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.92
- alias: processing
  name: flight-processing
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
  tags:
    - full-deploy
- alias: api
  name: flight-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.4
  tags:
    - full-deploy

  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: flight-ui
  repository: file://../flight-ui
